// <auto-generated />
namespace PracticaE2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Erika : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Erika));
        
        string IMigrationMetadata.Id
        {
            get { return "202209082023381_Erika"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
